const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={status:null};
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json"},...options});let data={};try{data=await r.json()}catch{}if(!r.ok)throw new Error(data.error||`Request failed (${r.status})`);return data}
function toast(message,error=false){const n=$("#notice");n.innerHTML=`<div class="toast ${error?'error':''}">${escapeHtml(message)}</div>`;setTimeout(()=>n.innerHTML="",3500)}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v??"";return d.innerHTML}
function ago(value){if(!value)return "Never";const s=Math.max(0,Math.floor(Date.now()/1000-value));if(s<60)return `${s}s ago`;if(s<3600)return `${Math.floor(s/60)}m ago`;return `${Math.floor(s/3600)}h ago`}
function duration(s){const h=Math.floor(s/3600),m=Math.floor(s%3600/60);return h?`${h}h ${m}m`:`${m}m`}
async function loadStatus(){try{const s=state.status=await api("/api/status");$("#product-count").textContent=s.products;$("#keyword-count").textContent=s.keywords;$("#alert-count").textContent=s.lastAlerts;$("#side-status").textContent=`Up ${duration(s.uptime)} · ${s.checking?'Scanning now':`Last scan ${ago(s.lastCheck)}`}`;$("#check-btn").disabled=s.checking;$("#check-btn").textContent=s.checking?"Checking…":"Run check"}catch(e){$("#side-status").textContent="Connection lost"}}
function updateCountdown(){const s=state.status;if(!s?.nextCheck)return $("#countdown").textContent="Starting…";const left=Math.max(0,Math.floor(s.nextCheck-Date.now()/1000));$("#countdown").textContent=`${String(Math.floor(left/60)).padStart(2,"0")}:${String(left%60).padStart(2,"0")}`}
async function loadWatches(){const d=await api("/api/watches");$("#products-table").innerHTML=d.products.length?d.products.map(p=>`<tr><td><strong>#${p.product_id} · ${escapeHtml(p.state?.name||"Loading product…")}</strong><small>${escapeHtml(p.state?.url||"")}</small></td><td>${p.state?`${escapeHtml(p.state.price)} ${escapeHtml(p.state.currency)}`:"—"}</td><td><span class="stock">${p.state?.stock??"—"}</span></td><td>${p.low_stock_threshold??"Global default"}</td><td>${p.z2u?`<span class="tag">${escapeHtml(p.z2u.status)}</span><small>${p.z2u.offer_id?`ID ${escapeHtml(p.z2u.offer_id)}`:"No offer ID yet"}</small>`:"Not listed"}</td><td><div class="row-actions"><button class="btn z2u-btn" data-list-z2u="${p.product_id}">List on Z2U</button><button class="remove" data-remove-product="${p.product_id}">Remove</button></div></td></tr>`).join(""):`<tr><td colspan="6" class="empty">No products watched yet.</td></tr>`;$("#keyword-cards").innerHTML=d.keywords.length?d.keywords.map(k=>`<article class="card"><span class="tag">ALL WORDS</span><h3>${escapeHtml(k.keywords)}</h3><p>Watching the full catalog for new lowest-price listings and price drops.</p><div class="card-foot"><small>Watch #${k.id}</small><button class="remove" data-remove-keyword="${k.id}">Remove</button></div></article>`).join(""):`<article class="panel empty">No keyword watches yet.</article>`}
async function loadActivity(){const d=await api("/api/activity");$("#activity").innerHTML=d.items.length?d.items.slice(0,6).map(a=>`<div class="activity-item ${a.kind}"><i></i><span>${escapeHtml(a.message)}</span><small>${escapeHtml(a.created_at)}</small></div>`).join(""):`<p class="empty">No activity yet.</p>`}
async function addProduct(form){const data=Object.fromEntries(new FormData(form));await api("/api/products",{method:"POST",body:JSON.stringify(data)});form.reset();form.closest("dialog")?.close();toast("Product watch added");await refresh()}
async function addKeyword(form){const data=Object.fromEntries(new FormData(form));await api("/api/keywords",{method:"POST",body:JSON.stringify(data)});form.reset();form.closest("dialog")?.close();toast("Keyword watch added");await refresh()}
async function refresh(){await Promise.all([loadStatus(),loadWatches(),loadActivity()])}
$$('[data-page]').forEach(b=>b.onclick=()=>{$$('.nav,.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(`#${b.dataset.page}`).classList.add('active');$("#page-title").textContent=b.textContent.trim()});
$$('[data-dialog]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.dialog).showModal());
$("#quick-product").onsubmit=async e=>{e.preventDefault();try{await addProduct(e.target)}catch(x){toast(x.message,true)}};
$("#product-dialog form").onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return e.target.closest('dialog').close();try{await addProduct(e.target)}catch(x){toast(x.message,true)}};
$("#keyword-dialog form").onsubmit=async e=>{e.preventDefault();if(e.submitter?.value==='cancel')return e.target.closest('dialog').close();try{await addKeyword(e.target)}catch(x){toast(x.message,true)}};
$("#check-btn").onclick=async()=>{try{await api("/api/check",{method:"POST",body:"{}"});toast("Catalog check started");loadStatus()}catch(e){toast(e.message,true)}};
$("#test-btn").onclick=async()=>{try{await api("/api/telegram/test",{method:"POST",body:"{}"});toast("Telegram notification sent");loadActivity()}catch(e){toast(e.message,true)}};
$("#refresh-activity").onclick=loadActivity;
async function listOnZ2U(productId){if(!window.hstoraExtensionReady)return toast("Install and configure the HStora Z2U Assistant extension first",true);const profit=prompt("Profit to add per unit in USD:","0.20");if(profit===null)return;if(!/^\d+(\.\d+)?$/.test(profit))return toast("Enter a valid non-negative profit",true);if(!confirm("The extension will open Z2U, fill the offer, accept the selected terms, and submit it. Continue?"))return;try{const listing=await api(`/api/products/${productId}/listing?profit=${encodeURIComponent(profit)}`);window.postMessage({source:"hstora-watcher",type:"LIST_ON_Z2U",listing},location.origin);toast("Opening Z2U listing assistant…")}catch(x){toast(x.message,true)}}
document.body.onclick=async e=>{const p=e.target.dataset.removeProduct,k=e.target.dataset.removeKeyword,z=e.target.dataset.listZ2u;try{if(p){await api(`/api/products/${p}`,{method:"DELETE"});toast("Product watch removed");refresh()}if(k){await api(`/api/keywords/${k}`,{method:"DELETE"});toast("Keyword watch removed");refresh()}if(z)listOnZ2U(z)}catch(x){toast(x.message,true)}};
$("#search-form").onsubmit=async e=>{e.preventDefault();const form=new FormData(e.target),q=form.get("q"),sort=form.get("sort");const box=$("#search-results"),summary=$("#search-summary");box.innerHTML='<article class="panel empty">Scanning the complete catalog…</article>';summary.textContent="";try{const d=await api(`/api/search?q=${encodeURIComponent(q)}&sort=${encodeURIComponent(sort)}`);summary.textContent=`${d.total} matching product${d.total===1?'':'s'} · showing up to 100`;box.innerHTML=d.items.length?d.items.map(p=>`<article class="card result-card"><div class="result-price">${escapeHtml(p.price)} <small>${escapeHtml(p.currency)}</small></div><h3><a href="${escapeHtml(p.url)}" target="_blank" rel="noreferrer">${escapeHtml(p.name)}</a></h3><div class="result-meta"><span>#${p.id}</span><span class="stock">${p.stock} in stock</span>${p.z2u?`<span class="tag">Z2U: ${escapeHtml(p.z2u.status)}</span>`:""}</div><div class="card-foot"><button class="btn ghost watch-result" data-id="${p.id}">Watch product</button><button class="btn z2u-btn" data-list-z2u="${p.id}">List on Z2U</button></div></article>`).join(""):'<article class="panel empty">No matching products.</article>';$$('.watch-result').forEach(b=>b.onclick=async()=>{try{await api('/api/products',{method:'POST',body:JSON.stringify({productId:b.dataset.id})});toast('Product watch added');refresh()}catch(x){toast(x.message,true)}})}catch(x){box.innerHTML="";toast(x.message,true)}};
window.hstoraExtensionReady=false;window.addEventListener("message",e=>{if(e.origin!==location.origin||e.data?.source!=="hstora-z2u-extension")return;if(e.data.type==="EXTENSION_READY"){window.hstoraExtensionReady=true;$("#extension-state").textContent="Connected and ready";$("#extension-state").classList.add("connected")}if(e.data.type==="Z2U_STATUS"){toast(e.data.message,e.data.status==="failed");refresh()}});window.postMessage({source:"hstora-watcher",type:"PING_EXTENSION"},location.origin);
refresh().catch(e=>toast(e.message,true));setInterval(loadStatus,5000);setInterval(updateCountdown,1000);
